canton {
  participants {
    sandbox {
      storage {
        type = postgres
        config {
          dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
          properties = {
            serverName = "localhost"
            serverName = ${?CANTON_DB_HOST}
            portNumber = 5432
            portNumber = ${?CANTON_DB_PORT}
            databaseName = "canton_sandbox"
            databaseName = ${?CANTON_DB_NAME}
            user = "postgres"
            user = ${?CANTON_DB_USER}
            password = "password"
            password = ${?CANTON_DB_PASSWORD}
          }
        }
        max-connections = 32
        pool-size = 8
      }
      ledger-api {
        address = "0.0.0.0"
        port = 6865
        auth-services = [{
          type = wildcard
        }]
      }
      http-ledger-api-daemon {
        address = "0.0.0.0"
        port = 7575
      }
      admin-api {
        port = 26012
      }
    }
  }
}
