"""Smoke check for curated pattern loader + branding header.

Run from repo root:
    backend/venv/Scripts/python.exe backend/tests/_curated_smoke.py

Not pytest-discovered (filename starts with _).
"""
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from rag.curated_loader import get_curated_example, format_curated_for_prompt  # noqa: E402
from utils.branding import prepend_brand_header  # noqa: E402


# Each row: (pattern, domain, expected_stem)
CASES = [
    # exact alias hits via pattern
    ("voting-dao",            None,         "voting-dao"),
    ("soulbound-credential",  None,         "soulbound-credential"),
    ("escrow",                None,         "escrow"),
    ("nft",                   None,         "nft"),
    ("bond-tokenization",     None,         "bond-tokenization"),
    ("propose-accept",        None,         "propose-accept"),
    ("invoice-processing",    None,         "invoice-processing"),
    # alias keyword hits
    ("voting",                None,         "voting-dao"),
    ("dao",                   None,         "voting-dao"),
    ("badge",                 None,         "soulbound-credential"),
    ("certificate",           None,         "soulbound-credential"),
    ("bond",                  None,         "bond-tokenization"),
    # invoice / billing
    ("invoice",               None,         "invoice-processing"),
    ("billing",               None,         "invoice-processing"),
    ("bill",                  None,         "invoice-processing"),
    ("invoicing",             None,         "invoice-processing"),
    ("payment-request",       None,         "invoice-processing"),
    ("accounts-receivable",   None,         "invoice-processing"),
    # domain fallback when pattern is unknown
    (None,                    "credential", "soulbound-credential"),
    (None,                    "finance",    "bond-tokenization"),
    (None,                    "rights",     "nft"),
    (None,                    "governance", "voting-dao"),
    # substring match \u2014 longer alias should win
    ("soulbound-credential-token", None,    "soulbound-credential"),
    # complete miss
    ("xyzzy",                 "nonsense",   None),
    (None,                    None,         None),
]


def main() -> None:
    failures: list[str] = []
    for pattern, domain, expected in CASES:
        got = get_curated_example(pattern, domain)
        stem = got[0] if got else None
        if stem != expected:
            failures.append(f"  pattern={pattern!r} domain={domain!r}: got {stem!r}, expected {expected!r}")

    if failures:
        print("FAIL \u2014 curated loader resolution mismatches:")
        for f in failures:
            print(f)
        sys.exit(1)

    # Format check: voting-dao should produce a non-empty prompt block
    block = format_curated_for_prompt("voting", None)
    assert "GOLD-STANDARD REFERENCE" in block
    assert "voting-dao" in block
    assert "voters : [Party]" in block
    assert "VoteVoter1" in block  # the cautionary "NEVER do this" callout

    # Branding idempotence
    src = "module Main where\n\ntemplate X with p : Party where signatory p\n"
    once = prepend_brand_header(src, pattern="voting-dao", domain="governance", module_name="Main")
    twice = prepend_brand_header(once, pattern="voting-dao", domain="governance", module_name="Main")
    assert "Generated by Canton.Ginie" in once
    assert once == twice, "branding must be idempotent"
    assert once.count("Generated by Canton.Ginie") == 1

    # Self-audit: every curated example MUST itself pass the static
    # checker for DSV-016 / DSV-017::Pay* / DSV-017::Mark* / DSV-017::Settle*
    # so we never seed the writer's prompt with an example that violates
    # the rules we ask the LLM to follow.
    from security.static_checks import detect_static_findings  # noqa: E402
    curated_dir = os.path.join(ROOT, "rag", "curated")
    self_audit_failures: list[str] = []
    for fname in sorted(os.listdir(curated_dir)):
        if not fname.endswith(".daml"):
            continue
        with open(os.path.join(curated_dir, fname), encoding="utf-8") as fh:
            findings = detect_static_findings(fh.read())
        bad = [
            f for f in findings
            if f["id"].startswith("DSV-016::")
            or f["id"].startswith("DSV-017::Pay")
            or f["id"].startswith("DSV-017::Mark")
            or f["id"].startswith("DSV-017::Settle")
            or f["id"].startswith("DSV-017::Complete")
        ]
        if bad:
            for f in bad:
                self_audit_failures.append(f"  {fname}: [{f['severity']}] {f['id']}  {f['title']}")
    if self_audit_failures:
        print("FAIL \u2014 curated examples must pass their own static checks:")
        for line in self_audit_failures:
            print(line)
        sys.exit(1)

    print(f"curated loader + branding smoke OK ({len(CASES)} cases)")


if __name__ == "__main__":
    main()
